/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package multimidia;

/**
 *
 * @author VF_CASA
 */
public class GuiPrincipal extends javax.swing.JFrame {

    private DataBase dataBase = new DataBase();
    private GuiCadastroDVD dialogoCadastro = new GuiCadastroDVD(new java.awt.Frame(), true,dataBase);
    private GuiRelatorioDVD dialogoRelatorio = new GuiRelatorioDVD(new java.awt.Frame(), true,dataBase);
    private GuiTelaSobre dialogoSobre = new GuiTelaSobre(this, true);
    private GuiCadastroMoto dialogoCadastroCD = new GuiCadastroMoto(new java.awt.Frame(), true,dataBase);
    private GuiRelatorio dialogoRelatorioCD = new GuiRelatorio(new java.awt.Frame(),true,dataBase);
    /**
     * Creates new form GuiPrincipal
     */
    public GuiPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jM_Cadastro = new javax.swing.JMenu();
        jMI_CadastroDVD = new javax.swing.JMenuItem();
        jMI_CadastroCD = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMI_RelatorioDVD = new javax.swing.JMenuItem();
        jMI_RelatorioCD = new javax.swing.JMenuItem();
        jM_Sobre = new javax.swing.JMenu();
        jMI_Informacao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jM_Cadastro.setText("Cadastro");

        jMI_CadastroDVD.setText("DVD");
        jMI_CadastroDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_CadastroDVDActionPerformed(evt);
            }
        });
        jM_Cadastro.add(jMI_CadastroDVD);

        jMI_CadastroCD.setText("CD");
        jMI_CadastroCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_CadastroCDActionPerformed(evt);
            }
        });
        jM_Cadastro.add(jMI_CadastroCD);

        jMenuBar1.add(jM_Cadastro);

        jMenu2.setText("Relatorio");

        jMI_RelatorioDVD.setText("DVD");
        jMI_RelatorioDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_RelatorioDVDActionPerformed(evt);
            }
        });
        jMenu2.add(jMI_RelatorioDVD);

        jMI_RelatorioCD.setText("CD");
        jMI_RelatorioCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_RelatorioCDActionPerformed(evt);
            }
        });
        jMenu2.add(jMI_RelatorioCD);

        jMenuBar1.add(jMenu2);

        jM_Sobre.setText("Sobre");
        jM_Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_SobreActionPerformed(evt);
            }
        });

        jMI_Informacao.setText("Informações");
        jMI_Informacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_InformacaoActionPerformed(evt);
            }
        });
        jM_Sobre.add(jMI_Informacao);

        jMenuBar1.add(jM_Sobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMI_CadastroCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_CadastroCDActionPerformed
        // TODO add your handling code here:
        dialogoCadastroCD.setVisible(true);
    }//GEN-LAST:event_jMI_CadastroCDActionPerformed

    private void jMI_RelatorioDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_RelatorioDVDActionPerformed
        // TODO add your handling code here:
        dialogoRelatorio.setVisible(true);
    }//GEN-LAST:event_jMI_RelatorioDVDActionPerformed

    private void jM_SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_SobreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jM_SobreActionPerformed

    private void jMI_CadastroDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_CadastroDVDActionPerformed
        // TODO add your handling code here:
        dialogoCadastro.setVisible(true);
    }//GEN-LAST:event_jMI_CadastroDVDActionPerformed

    private void jMI_InformacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_InformacaoActionPerformed
        // TODO add your handling code here:
        dialogoSobre.setVisible(true);
    }//GEN-LAST:event_jMI_InformacaoActionPerformed

    private void jMI_RelatorioCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_RelatorioCDActionPerformed
        // TODO add your handling code here:
        dialogoRelatorioCD.setVisible(true);
    }//GEN-LAST:event_jMI_RelatorioCDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMI_CadastroCD;
    private javax.swing.JMenuItem jMI_CadastroDVD;
    private javax.swing.JMenuItem jMI_Informacao;
    private javax.swing.JMenuItem jMI_RelatorioCD;
    private javax.swing.JMenuItem jMI_RelatorioDVD;
    private javax.swing.JMenu jM_Cadastro;
    private javax.swing.JMenu jM_Sobre;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
