package Prova;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author valer
 */
public class GuiPrincipal extends javax.swing.JFrame {
    private DataBase dataBase = new DataBase();
    private GuiCadastroCarro dialogoCadastroCarro = new GuiCadastroCarro(new java.awt.Frame(), true,dataBase);
    private GuiTelaSobre dialogoSobre = new GuiTelaSobre(this, true);
    private GuiCadastroMoto dialogoCadastroMoto = new GuiCadastroMoto(new java.awt.Frame(), true,dataBase);
    private GuiRelatorio dialogoRelatorio = new GuiRelatorio(new java.awt.Frame(),true,dataBase);
    /**
     * Creates new form GuiPrincipal
     */
    public GuiPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JMenu = new javax.swing.JMenuBar();
        JM_Cadastro = new javax.swing.JMenu();
        JMI_CadastroCarro = new javax.swing.JMenuItem();
        JMI_CadastroMoto = new javax.swing.JMenuItem();
        JM_Relatorio = new javax.swing.JMenu();
        JMI_Relatorio = new javax.swing.JMenuItem();
        JM_Sobre = new javax.swing.JMenu();
        JMI_Informacoes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JM_Cadastro.setText("Cadastro");

        JMI_CadastroCarro.setText("Cadastro Carro");
        JMI_CadastroCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CadastroCarroActionPerformed(evt);
            }
        });
        JM_Cadastro.add(JMI_CadastroCarro);

        JMI_CadastroMoto.setText("Cadastro Moto");
        JMI_CadastroMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CadastroMotoActionPerformed(evt);
            }
        });
        JM_Cadastro.add(JMI_CadastroMoto);

        JMenu.add(JM_Cadastro);

        JM_Relatorio.setText("Relatorio");

        JMI_Relatorio.setText("Relatorio");
        JMI_Relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_RelatorioActionPerformed(evt);
            }
        });
        JM_Relatorio.add(JMI_Relatorio);

        JMenu.add(JM_Relatorio);

        JM_Sobre.setText("Sobre");

        JMI_Informacoes.setText("Sobre");
        JMI_Informacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_InformacoesActionPerformed(evt);
            }
        });
        JM_Sobre.add(JMI_Informacoes);

        JMenu.add(JM_Sobre);

        setJMenuBar(JMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMI_CadastroCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CadastroCarroActionPerformed
        // TODO add your handling code here:
        dialogoCadastroCarro.setVisible(true);
    }//GEN-LAST:event_JMI_CadastroCarroActionPerformed

    private void JMI_CadastroMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CadastroMotoActionPerformed
        // TODO add your handling code here:
        dialogoCadastroMoto.setVisible(true);
    }//GEN-LAST:event_JMI_CadastroMotoActionPerformed

    private void JMI_InformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_InformacoesActionPerformed
        // TODO add your handling code here:
         dialogoSobre.setVisible(true);
    }//GEN-LAST:event_JMI_InformacoesActionPerformed

    private void JMI_RelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_RelatorioActionPerformed
        // TODO add your handling code here:
       
        dialogoRelatorio.setVisible(true);
    }//GEN-LAST:event_JMI_RelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMI_CadastroCarro;
    private javax.swing.JMenuItem JMI_CadastroMoto;
    private javax.swing.JMenuItem JMI_Informacoes;
    private javax.swing.JMenuItem JMI_Relatorio;
    private javax.swing.JMenu JM_Cadastro;
    private javax.swing.JMenu JM_Relatorio;
    private javax.swing.JMenu JM_Sobre;
    private javax.swing.JMenuBar JMenu;
    // End of variables declaration//GEN-END:variables
}
